---
- hosts: all
  become: true
  gather_facts: yes
  tasks:
   
    - name: Install Apache2 and php packages for Ubuntu and CentOS
      package:
        name:
          - "{{ apache_package }}"
          - "{{ php_package }} "
        state: latest
        update_cache: yes
    

    
